### PR TITLE
Add Discord RPC

### PR DESCRIPTION
**Pull request by SinnerTF2**
yeah

here is preview ig:
image

### CODE REVIEW

**Comment by l-r00t-l** [comment]
good shit

**Comment by SinnerTF2** [comment]
also just noticed visual studio had autism in What.cpp but it didnt change anything so sorry for the spaces it made

**Comment by cheekybaguette** [comment]
balls

**Comment by cheekybaguette** [comment]
read this in discord if gay

**Comment by cheekybaguette** [comment]
above gay

**Comment by cheekybaguette** [comment]
below gay

**Comment by M-FeD** [comment]
Cool

**Comment by cheekybaguette** [comment]
peasants talking in general while im here in #github

**Comment by cheekybaguette** [comment]
frelo is a retard btw u should block him

**Comment by cheekybaguette** [comment]
i know this wont work but i gotta try anyway @everyone

**Comment by cheekybaguette** [comment]
well that was expected

**Comment by cheekybaguette** [comment]
https://rijin.solutions on top baby

**Pull request merged**
