### PR TITLE
add always fire dt

### PR DESCRIPTION
**Pull request by HutchyBean**

### CODE REVIEW

**Comment by km-ch** [comment]
This is useless, you can just bind the dt button to MOUSE1 and it will do the same thing

**Comment by HutchyBean** [comment]
Lots of people don't bind their aim key to mouse 1.

**Comment by HutchyBean** [comment]
Although a drop-down with options for. on key, always DT, disable on key would probably be better now that i think about it

**Comment by M-FeD** [comment]
> 
> 
> Although a drop-down with options for. on key, always DT, disable on key would probably be better now that i think about it

Add this and I will merge

**Comment by km-ch** [comment]
Remember to add Vars::Misc::CL_Move::DoubletapKey to ConfigManager.cpp

**Comment by km-ch** [comment]
https://github.com/HutchyBean/Fedoraware/pull/1

**Pull request merged**
