### PR TITLE
Various additions and improvements

### PR DESCRIPTION
**Pull request by lnx00**
- Fixed issue #199 
- Fixed skybox not being saved in a config
- Added more chat spam (Lmaobox, Cathook)
- Added more shortcuts in the menu bar
- Added custom Rage Retry health limit
- Various fixes and improvements

### CODE REVIEW

**Comment by M-FeD** [comment]
The core folder was for the skin changer config

**Comment by M-FeD** [comment]
Can u add it back before I accept the pr?

**Comment by lnx00** [comment]
sure, gimme a second

**Comment by lnx00** [comment]
There we go

**Comment by M-FeD** [comment]
Cheers

**Pull request merged**
