### PR TITLE
why the fuck did this get commented

### PR DESCRIPTION
**Pull request by km-ch**
seriously

### CODE REVIEW

**Comment by HutchyBean** [comment]
cause its checked in line 73

**Comment by HutchyBean** [comment]
owned. thought he had a smart moment

**Comment by HutchyBean** [comment]
actually never mind it needs changing

**Comment by HutchyBean** [comment]
change that to only run when not teammate

**Comment by km-ch** [comment]
it still won't ignore friends in the other team
yes i have ignore friends enabled

**Comment by M-FeD** [comment]
because it makes the whip ignore friends who are on your own team?

**Comment by JAGNEmk** [comment]
**Considering this closed - there is a valid reason for it being commented out**

**Pull request closed without merging**
