### PR TITLE
this is spelling + toggle for server angels

### PR DESCRIPTION
**Pull request by HutchyBean**

### CODE REVIEW

**Comment by lnx00** [comment]
You forgot to save and load the server angle toggle in the ConfigManager.
Make sure to include the corresponding `SAVE_VAR` and `LOAD_VAR` entries in ConfigManager.cpp

**Comment by HutchyBean** [comment]
dude. i honestly forget all the time (cause my config is way better)

**Comment by HutchyBean** [comment]
hutchybenware config manager >>> poopware (fedorawware)

**Comment by lnx00** [comment]
c35a46a7fc258425bc2c5166bfbae81c0d4a22aa mad lol

**Comment by M-FeD** [comment]
Thank you ben

**Pull request merged**
