### PR TITLE
add github action to like automatically check if it builds and give dll to brainlets

### PR DESCRIPTION
**Pull request by HutchyBean**
i am also a brainlet as it took 9 commits (i was edittingin on github) to get it working.

### CODE REVIEW

**Comment by HutchyBean** [comment]
yes it doesnt crash. yes it works. yes i tested the dll

**Comment by cheekybaguette** [comment]
nigga balls

**Comment by HutchyBean** [comment]
yo i wonder if you can ping everyone in t hese

**Comment by HutchyBean** [comment]
@everyone <@everyone>

**Comment by HutchyBean** [comment]
aww

**Comment by cheekybaguette** [comment]
cant do that through embeds at all

**Comment by HutchyBean** [comment]
cool.

**Comment by cheekybaguette** [comment]
not cool cause i wanted to spam ._.

**Comment by SinnerTF2** [comment]
epic

**Comment by M-FeD** [comment]
okay

**Pull request merged**
