### PR TITLE
dt but like it dt's when not using autoshoot

### PR DESCRIPTION
**Pull request by HutchyBean**
i dont know how c plu splus works. i dont know how tf2 fedoraware works.

### CODE REVIEW

**Comment by M-FeD** [comment]
does it work

**Comment by HutchyBean** [comment]
yuh

**Comment by M-FeD** [comment]
okay

**Comment by M-FeD** [comment]
does it crash

**Comment by HutchyBean** [comment]
no

**Comment by M-FeD** [comment]
g_GlobalInfo.m_bAttacking = pCmd->buttons & IN_ATTACK;
please dont do this

**Comment by HutchyBean** [comment]
i did it

**Comment by M-FeD** [comment]
you actual mongoloid

**Comment by M-FeD** [comment]
no offense

**Comment by HutchyBean** [comment]
thank you

**Comment by IamIndeedGamingAsHardAsICan03489** [comment]
do it at the end of create move

**Comment by HutchyBean** [comment]
use lateUsercmd?

**Comment by M-FeD** [comment]
> 
> 
> use lateUsercmd?

thats some retarded thing for the crit funny thing dont what?

**Comment by HutchyBean** [comment]
i can use it therte aswell i think

**Comment by M-FeD** [comment]
fuck you

**Comment by Rocketmanz1** [comment]
shut up bruv

**Pull request merged**
